version: '2'

services:

  redis:
    image: 'redis:7.2-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'redis'
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/1
      - APP_HOST
      - USE_HTTP_REDIRECT=1
    ports:
      - '3001:3000'

volumes:
  redis:
